export const  PRODUCT_CATEGORIES = [
    "Electronics",
    "Cameras",
    "Laptops",
    "Kitchen & Dining",
    "Personal Care",
    "Stationery",
    "Sports & Outdoors",
    "Accessories",
    "Headphones",
    "Food",
    "Books",
    "Sports",
    "Outdoor",
    "Home",
]